### PR TITLE
Feature aurion

### PR DESCRIPTION
**Pull request by aurion-cloud**

### CODE REVIEW

**Comment by aurion-cloud** [comment]
added main-playbook for kibana and updated inventory hosts

**Comment by alexbenavente-cloudreach** [comment]
Looks good to me.

**Review by Amanda-Ruzza — COMMENTED** [review]
I see that you erased the RSA .PEM file, but somehow, we can still view it in the "diff" feature of Github. Maybe that will no longer be viewable once we merge the branch?

**Comment by Amanda-Ruzza** [comment]
I read everything, and it looks good to me. Just one suggestion: maybe in the future, instead of naming your branch "feature_aurion", maybe, just name your branch with the feature that you're working on, so its clear for other engineers to take a look at it, something like "kibana"

**Pull request merged**
